// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pb/coupons.proto

package couponsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coupons_CreateNewCoupon_FullMethodName = "/coupons.v1.Coupons/CreateNewCoupon"
)

// CouponsClient is the client API for Coupons service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponsClient interface {
	CreateNewCoupon(ctx context.Context, in *AddNewCouponRequest, opts ...grpc.CallOption) (*AddNewCouponResponse, error)
}

type couponsClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponsClient(cc grpc.ClientConnInterface) CouponsClient {
	return &couponsClient{cc}
}

func (c *couponsClient) CreateNewCoupon(ctx context.Context, in *AddNewCouponRequest, opts ...grpc.CallOption) (*AddNewCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNewCouponResponse)
	err := c.cc.Invoke(ctx, Coupons_CreateNewCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponsServer is the server API for Coupons service.
// All implementations must embed UnimplementedCouponsServer
// for forward compatibility.
type CouponsServer interface {
	CreateNewCoupon(context.Context, *AddNewCouponRequest) (*AddNewCouponResponse, error)
	mustEmbedUnimplementedCouponsServer()
}

// UnimplementedCouponsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCouponsServer struct{}

func (UnimplementedCouponsServer) CreateNewCoupon(context.Context, *AddNewCouponRequest) (*AddNewCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewCoupon not implemented")
}
func (UnimplementedCouponsServer) mustEmbedUnimplementedCouponsServer() {}
func (UnimplementedCouponsServer) testEmbeddedByValue()                 {}

// UnsafeCouponsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponsServer will
// result in compilation errors.
type UnsafeCouponsServer interface {
	mustEmbedUnimplementedCouponsServer()
}

func RegisterCouponsServer(s grpc.ServiceRegistrar, srv CouponsServer) {
	// If the following call pancis, it indicates UnimplementedCouponsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coupons_ServiceDesc, srv)
}

func _Coupons_CreateNewCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).CreateNewCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupons_CreateNewCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).CreateNewCoupon(ctx, req.(*AddNewCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coupons_ServiceDesc is the grpc.ServiceDesc for Coupons service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coupons_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coupons.v1.Coupons",
	HandlerType: (*CouponsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewCoupon",
			Handler:    _Coupons_CreateNewCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/coupons.proto",
}
