// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: pb/coupons.proto

package couponsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNewCouponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Multiplier  float32 `protobuf:"fixed32,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
}

func (x *AddNewCouponRequest) Reset() {
	*x = AddNewCouponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coupons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewCouponRequest) ProtoMessage() {}

func (x *AddNewCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coupons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewCouponRequest.ProtoReflect.Descriptor instead.
func (*AddNewCouponRequest) Descriptor() ([]byte, []int) {
	return file_pb_coupons_proto_rawDescGZIP(), []int{0}
}

func (x *AddNewCouponRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddNewCouponRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddNewCouponRequest) GetMultiplier() float32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type AddNewCouponResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddNewCouponResponse) Reset() {
	*x = AddNewCouponResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coupons_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewCouponResponse) ProtoMessage() {}

func (x *AddNewCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coupons_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewCouponResponse.ProtoReflect.Descriptor instead.
func (*AddNewCouponResponse) Descriptor() ([]byte, []int) {
	return file_pb_coupons_proto_rawDescGZIP(), []int{1}
}

func (x *AddNewCouponResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_pb_coupons_proto protoreflect.FileDescriptor

var file_pb_coupons_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x6d,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x26, 0x0a,
	0x14, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0x5f, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73,
	0x12, 0x54, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x78, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x3b,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa,
	0x02, 0x0a, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x43, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x0b, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_coupons_proto_rawDescOnce sync.Once
	file_pb_coupons_proto_rawDescData = file_pb_coupons_proto_rawDesc
)

func file_pb_coupons_proto_rawDescGZIP() []byte {
	file_pb_coupons_proto_rawDescOnce.Do(func() {
		file_pb_coupons_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_coupons_proto_rawDescData)
	})
	return file_pb_coupons_proto_rawDescData
}

var file_pb_coupons_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_coupons_proto_goTypes = []any{
	(*AddNewCouponRequest)(nil),  // 0: coupons.v1.AddNewCouponRequest
	(*AddNewCouponResponse)(nil), // 1: coupons.v1.AddNewCouponResponse
}
var file_pb_coupons_proto_depIdxs = []int32{
	0, // 0: coupons.v1.Coupons.CreateNewCoupon:input_type -> coupons.v1.AddNewCouponRequest
	1, // 1: coupons.v1.Coupons.CreateNewCoupon:output_type -> coupons.v1.AddNewCouponResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_coupons_proto_init() }
func file_pb_coupons_proto_init() {
	if File_pb_coupons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_coupons_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddNewCouponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coupons_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddNewCouponResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_coupons_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_coupons_proto_goTypes,
		DependencyIndexes: file_pb_coupons_proto_depIdxs,
		MessageInfos:      file_pb_coupons_proto_msgTypes,
	}.Build()
	File_pb_coupons_proto = out.File
	file_pb_coupons_proto_rawDesc = nil
	file_pb_coupons_proto_goTypes = nil
	file_pb_coupons_proto_depIdxs = nil
}
